### ISSUE TITLE
where can I get the data sampling_input_kurgan.txt

### ISSUE THREAD

**Issue by TomasZhang19** [fsleeman/spark-class-balancing#1]
Dear author,
In the example.scala, there is a file path "/home/ford/data/sampling_input_kurgan.txt". Could you please tell me how to get the sampling_input_kurgan.txt?

**Comment by fsleeman** [comment]
That file has been replaced with an example input file with the format used for scripting the experiments in the paper. You use that format or change the input method as needed in the example.scala file.
